services:
  db:
    image: postgres:17-alpine
    container_name: studystreak-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - studystreak_postgres_data:/var/lib/postgresql/data

  app:
    build: .  # Use the Dockerfile created
    container_name: studystreak-app

    # Send values from Docker compose into spring boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${APP_PORT}:8080"

    # Start db before app
    depends_on:
      - db

volumes:
  studystreak_postgres_data: