spring.application.name=StudyStreak

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studystreak}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:studystreak}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:studystreak_dev_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret = ${JWT_SECRET}
jwt.expiration = ${JWT_EXPIRATION}

#SMTP credenciales de MailTRAP
# (fase de testing, en fases mas avanzadas del proyecto se configurara una cuenta real gmail)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=cdfec351f6004f
spring.mail.password=fac66129f95fc1