spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.data-source-properties.sslmode=verify-full
spring.datasource.hikari.data-source-properties.sslrootcert=/app/certs/global-bundle.pem
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=8080
server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

server.error.include-message=never
server.error.include-stacktrace=never

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}