spring.application.name=StudyStreak
spring.datasource.url=jdbc:postgresql://localhost:5432/StudyStreak
spring.datasource.username=postgres
spring.datasource.password=Landeo01_@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true